-- Catalog services imported from Kynd_Service_Master_4.xlsx ("Service Master" tab).
-- Generated, not hand-written. 119 rows: 111 live, 8 pending_rates (Office
-- Cleaning + Pest Control have no prices in the sheet yet).
--
-- Requires backend/db/seed/catalog-taxonomy.sql to have run first (categories
-- 1/3/4/5/6 and subcategories 103-501). The sheet's Single Session / One-Time /
-- Weekly Package groups all sit under General Package (103).
--
-- markup_pct_override is derived per row as (Sell / Partner Cost - 1) x 100 so
-- that the price the storefront shows is exactly the sheet's "Sell Price
-- (final)" — the flat 30%% target rounds to a different dollar on ~20 rows.
-- The authoritative customer price is also stored as a `flat` pricing rule.
--
-- Partner Cost is the sheet's "Total Partner Cost". Per the README those values
-- are BACK-CALCULATED from the old sell price for Cleaning rows, not real
-- partner quotes — replace them as partners are negotiated.
--
-- Idempotent (explicit ids + ON DUPLICATE KEY UPDATE).
--
--   mysql -u root -p urban_service < backend/db/seed/catalog-services.sql

USE urban_service;

INSERT INTO catalog_services
  (id, category_id, subcategory_id, name, description, duration, status,
   default_partner_cost, markup_pct_override, competitor_reference, notes)
VALUES
  (1001, 1, 103, 'Single Session 1.0 hr', 'Ad-hoc single visit - 1 worker(s), 1 hrs', '1 hr', 'live', 23.00, 30.43, 'Kynd ad-hoc ~$26-28/hr is mid-market, above Urban Company''s ad-hoc $24-27/hr.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (1 hrs x S$23 = S$23.00). Price increase passed to customer: S$28 -> S$30. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1002, 1, 103, 'Single Session 1.5 hr', 'Ad-hoc single visit - 1 worker(s), 1.5 hrs', '1.5 hrs', 'live', 34.50, 30.43, 'Kynd ad-hoc ~$26-28/hr is mid-market, above Urban Company''s ad-hoc $24-27/hr.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (1.5 hrs x S$23 = S$34.50). Price increase passed to customer: S$35 -> S$45. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1003, 1, 103, 'Single Session 2.0 hr', 'Ad-hoc single visit - 1 worker(s), 2 hrs', '2 hrs', 'live', 46.00, 30.43, 'Kynd ad-hoc ~$26-28/hr is mid-market, above Urban Company''s ad-hoc $24-27/hr.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (2 hrs x S$23 = S$46.00). Price increase passed to customer: S$55 -> S$60. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1004, 1, 103, 'One-Time Cleaning 2.0 hr', 'Single one-time booking - 1 worker(s), 2 hrs', '2 hrs', 'live', 46.00, 30.43, 'Kynd ad-hoc rate is mid-market vs Urban Company''s $24-27/hr ad-hoc range.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (2 hrs x S$23 = S$46.00). Price increase passed to customer: S$56 -> S$60. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1005, 1, 103, 'One-Time Cleaning 2.5 hr', 'Single one-time booking - 1 worker(s), 2.5 hrs', '2.5 hrs', 'live', 57.50, 30.43, 'Kynd ad-hoc rate is mid-market vs Urban Company''s $24-27/hr ad-hoc range.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (2.5 hrs x S$23 = S$57.50). Price increase passed to customer: S$65 -> S$75. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1006, 1, 103, 'One-Time Cleaning 3.0 hr', 'Single one-time booking - 1 worker(s), 3 hrs', '3 hrs', 'live', 69.00, 30.43, 'Kynd ad-hoc rate is mid-market vs Urban Company''s $24-27/hr ad-hoc range.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (3 hrs x S$23 = S$69.00). Price increase passed to customer: S$78 -> S$90. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1007, 1, 103, 'One-Time Cleaning 4.0 hr', 'Single one-time booking - 1 worker(s), 4 hrs', '4 hrs', 'live', 92.00, 30.43, 'Kynd ad-hoc rate is mid-market vs Urban Company''s $24-27/hr ad-hoc range.', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (4 hrs x S$23 = S$92.00). Price increase passed to customer: S$105 -> S$120. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1008, 1, 103, 'General Package 2hr (single)', 'One-time price, 2hr - 1 worker(s), 2 hrs', '2 hrs', 'live', 46.00, 30.43, 'Compare against Urban Company''s ad-hoc/recurring rates ($19-27/hr depending on frequency).', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (2 hrs x S$23 = S$46.00). Price increase passed to customer: S$50 -> S$60. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1009, 1, 103, 'General Package 3hr (single)', 'One-time price, 3hr - 1 worker(s), 3 hrs', '3 hrs', 'live', 69.00, 30.43, 'Compare against Urban Company''s ad-hoc/recurring rates ($19-27/hr depending on frequency).', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (3 hrs x S$23 = S$69.00). Price increase passed to customer: S$75 -> S$90. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1010, 1, 103, 'General Package 4hr (single)', 'One-time price, 4hr - 1 worker(s), 4 hrs', '4 hrs', 'live', 92.00, 30.43, 'Compare against Urban Company''s ad-hoc/recurring rates ($19-27/hr depending on frequency).', 'Negotiated partner rate: S$23/hr (8am-6pm), S$18/hr (7-10pm) - day rate applied here (4 hrs x S$23 = S$92.00). Price increase passed to customer: S$85 -> S$120. For evening bookings, use S$18/hr in the Partner Cost cell instead.'),
  (1011, 1, 103, 'General Package 2hr x4 sessions', '4-session bundle, 2hr/visit, redeem anytime within validity - 1 worker(s), 8 hrs', '8 hrs', 'live', 144.62, 30.00, 'Compare against Urban Company''s ad-hoc/recurring rates ($19-27/hr depending on frequency).', '3-month validity; price is for all 4 sessions combined NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1012, 1, 103, 'General Package 3hr x4 sessions', '4-session bundle, 3hr/visit, redeem anytime within validity - 1 worker(s), 12 hrs', '12 hrs', 'live', 211.54, 30.00, 'Compare against Urban Company''s ad-hoc/recurring rates ($19-27/hr depending on frequency).', '3-month validity; price is for all 4 sessions combined NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1013, 1, 103, 'General Package 4hr x4 sessions', '4-session bundle, 4hr/visit, redeem anytime within validity - 1 worker(s), 16 hrs', '16 hrs', 'live', 246.15, 30.00, 'Compare against Urban Company''s ad-hoc/recurring rates ($19-27/hr depending on frequency).', '3-month validity; price is for all 4 sessions combined NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1014, 1, 103, '2 Hours/Visit - 2 Times per Week', '2 Times per Week, 2.0hr/visit, 8 sessions/month (S$39/session) - 1 worker(s), 16 hrs', '16 hrs', 'live', 240.00, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 8 sessions x S$39/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1015, 1, 103, '2 Hours/Visit - 3 Times per Week', '3 Times per Week, 2.0hr/visit, 12 sessions/month (S$38/session) - 1 worker(s), 24 hrs', '24 hrs', 'live', 350.77, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 12 sessions x S$38/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1016, 1, 103, '2 Hours/Visit - 4 Times per Week', '4 Times per Week, 2.0hr/visit, 16 sessions/month (S$38/session) - 1 worker(s), 32 hrs', '32 hrs', 'live', 467.69, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 16 sessions x S$38/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1017, 1, 103, '3 Hours/Visit - 2 Times per Week', '2 Times per Week, 3.0hr/visit, 8 sessions/month (S$70/session) - 1 worker(s), 24 hrs', '24 hrs', 'live', 430.77, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 8 sessions x S$70/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1018, 1, 103, '3 Hours/Visit - 3 Times per Week', '3 Times per Week, 3.0hr/visit, 12 sessions/month (S$68/session) - 1 worker(s), 36 hrs', '36 hrs', 'live', 627.69, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 12 sessions x S$68/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1019, 1, 103, '3 Hours/Visit - 4 Times per Week', '4 Times per Week, 3.0hr/visit, 16 sessions/month (S$68/session) - 1 worker(s), 48 hrs', '48 hrs', 'live', 836.92, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 16 sessions x S$68/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1020, 1, 103, '4 Hours/Visit - 2 Times per Week', '2 Times per Week, 4.0hr/visit, 8 sessions/month (S$90/session) - 1 worker(s), 32 hrs', '32 hrs', 'live', 553.85, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 8 sessions x S$90/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1021, 1, 103, '4 Hours/Visit - 3 Times per Week', '3 Times per Week, 4.0hr/visit, 12 sessions/month (S$85/session) - 1 worker(s), 48 hrs', '48 hrs', 'live', 784.62, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 12 sessions x S$85/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1022, 1, 103, '4 Hours/Visit - 4 Times per Week', '4 Times per Week, 4.0hr/visit, 16 sessions/month (S$80/session) - 1 worker(s), 64 hrs', '64 hrs', 'live', 984.62, 30.00, 'Kynd recurring ~$19-23/hr is at/below Urban Company''s recurring rate (~$19-20/hr) and rest of market.', 'Monthly package price; 16 sessions x S$80/session; 1-month validity NEEDS INPUT: partner has re-negotiated ad-hoc rate to S$23/hr (day) / S$18/hr (evening), but that''s an ad-hoc rate - applying it flat here would erase this row''s volume/package discount (e.g. would roughly triple some package prices). Left at the old back-calculated cost pending a specific recurring/package rate from the partner.'),
  (1023, 1, 105, 'Studio Move-Out', '400-599 sqft - 2 worker(s), 3.5 hrs', '3.5 hrs', 'live', 207.69, 30.00, 'Urban Company starts "from $350" with a 3-person crew + auto-scrubber - undercuts/matches Kynd''s 4BR+ tiers ($510-550), with heavier equipment. UC didn''t disclose granular size tiers.', 'Duration range 3-4 hrs, used midpoint'),
  (1024, 1, 105, '2BR Move-Out (600-799 sqft)', '600-799 sqft - 3 worker(s), 4.5 hrs', '4.5 hrs', 'live', 246.15, 30.00, 'Urban Company starts "from $350" with a 3-person crew + auto-scrubber - undercuts/matches Kynd''s 4BR+ tiers ($510-550), with heavier equipment. UC didn''t disclose granular size tiers.', 'Team 2-3 per source doc; used 3 (rounded up, not 2.5) for a conservative cost estimate. Duration range 4-5 hrs, used midpoint 4.5 hrs.'),
  (1025, 1, 105, '2BR Move-Out (800-999 sqft)', '800-999 sqft - 3 worker(s), 5.5 hrs', '5.5 hrs', 'live', 300.00, 30.00, 'Urban Company starts "from $350" with a 3-person crew + auto-scrubber - undercuts/matches Kynd''s 4BR+ tiers ($510-550), with heavier equipment. UC didn''t disclose granular size tiers.', 'Duration range 5-6 hrs, used midpoint'),
  (1026, 1, 105, '3BR Move-Out', '1000-1199 sqft - 4 worker(s), 6.5 hrs', '6.5 hrs', 'live', 346.15, 30.00, 'Urban Company starts "from $350" with a 3-person crew + auto-scrubber - undercuts/matches Kynd''s 4BR+ tiers ($510-550), with heavier equipment. UC didn''t disclose granular size tiers.', 'Team 3-4 per source doc; used 4 (rounded up, not 3.5) for a conservative cost estimate. Duration range 6-7 hrs, used midpoint 6.5 hrs.'),
  (1027, 1, 105, '4BR Move-Out', '1200-1399 sqft - 4 worker(s), 7.5 hrs', '7.5 hrs', 'live', 392.31, 30.00, 'Urban Company starts "from $350" with a 3-person crew + auto-scrubber - undercuts/matches Kynd''s 4BR+ tiers ($510-550), with heavier equipment. UC didn''t disclose granular size tiers.', 'Duration range 7-8 hrs, used midpoint'),
  (1028, 1, 105, 'Maisonette / Large Move-Out', 'Large unit - 5 worker(s), 9 hrs', '9 hrs', 'live', 476.92, 30.00, 'Urban Company starts "from $350" with a 3-person crew + auto-scrubber - undercuts/matches Kynd''s 4BR+ tiers ($510-550), with heavier equipment. UC didn''t disclose granular size tiers.', 'Price range $590-$650, used midpoint $620. Team 4-5 per source doc; used 5 (rounded up, not 4.5) for a conservative cost estimate. Duration 8-10 hrs, used midpoint 9 hrs.'),
  (1029, 1, 106, 'Studio Move-Out (Condo)', 'Studio, incl. security/access/parking coordination - 2 worker(s), 3.5 hrs', '3.5 hrs', 'live', 230.77, 30.00, 'Urban Company starts "from $350" (3-person crew + auto-scrubber) - check against Kynd condo tiers.', 'Team/duration not stated in source doc; assumed same as HDB Studio'),
  (1030, 1, 106, '2BR Move-Out (600-799 sqft, Condo)', '600-799 sqft, incl. security/access/parking coordination - 3 worker(s), 4.5 hrs', '4.5 hrs', 'live', 269.23, 30.00, 'Urban Company starts "from $350" (3-person crew + auto-scrubber) - check against Kynd condo tiers.', 'Team/duration not stated for Condo; assumed same as HDB 2BR (600-799): 3 workers (rounded up from the HDB 2-3 range), 4.5 hrs.'),
  (1031, 1, 106, '2BR Move-Out (800-999 sqft, Condo)', '800-999 sqft, incl. security/access/parking coordination - 3 worker(s), 5.5 hrs', '5.5 hrs', 'live', 323.08, 30.00, 'Urban Company starts "from $350" (3-person crew + auto-scrubber) - check against Kynd condo tiers.', 'Team/duration assumed same as HDB 2BR (800-999)'),
  (1032, 1, 106, '3BR Move-Out (Condo)', 'incl. security/access/parking coordination - 4 worker(s), 6.5 hrs', '6.5 hrs', 'live', 369.23, 30.00, 'Urban Company starts "from $350" (3-person crew + auto-scrubber) - check against Kynd condo tiers.', 'Team/duration not stated for Condo; assumed same as HDB 3BR: 4 workers (rounded up from the HDB 3-4 range), 6.5 hrs.'),
  (1033, 1, 106, '4BR Move-Out (Condo)', 'incl. security/access/parking coordination - 4 worker(s), 7.5 hrs', '7.5 hrs', 'live', 423.08, 30.00, 'Urban Company starts "from $350" (3-person crew + auto-scrubber) - check against Kynd condo tiers.', 'Team/duration assumed same as HDB 4BR'),
  (1034, 1, 106, 'Penthouse / Large Move-Out (Condo)', 'incl. security/access/parking coordination - 5 worker(s), 9 hrs', '9 hrs', 'live', 538.46, 30.00, 'Urban Company starts "from $350" (3-person crew + auto-scrubber) - check against Kynd condo tiers.', 'Team/duration not stated for Condo; assumed same as HDB Maisonette: 5 workers (rounded up from the HDB 4-5 range), 9 hrs.'),
  (1035, 1, 107, 'Ceiling Fan Cleaning', 'Per unit add-on - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 11.54, 29.98, 'Urban Company also offers microwave cleaning $19, bathroom-only deep clean from $65, formaldehyde removal from $200 - none of which Kynd currently offers.', NULL),
  (1036, 1, 107, 'Refrigerator Cleaning', 'Per unit add-on - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 15.38, 30.04, 'Urban Company also offers microwave cleaning $19, bathroom-only deep clean from $65, formaldehyde removal from $200 - none of which Kynd currently offers.', NULL),
  (1037, 1, 107, 'Oven Deep Cleaning', 'Per unit add-on - 1 worker(s), 0.75 hrs', '0.75 hrs', 'live', 23.08, 29.98, 'Urban Company also offers microwave cleaning $19, bathroom-only deep clean from $65, formaldehyde removal from $200 - none of which Kynd currently offers.', NULL),
  (1038, 1, 107, 'Window Grilles & Frames', 'Per job add-on - 1 worker(s), 1 hrs', '1 hr', 'live', 38.46, 30.01, 'Urban Company also offers microwave cleaning $19, bathroom-only deep clean from $65, formaldehyde removal from $200 - none of which Kynd currently offers.', 'Price range $40-$60, used midpoint'),
  (1039, 1, 107, 'Curtains & Blinds Dusting', 'Per job add-on - 1 worker(s), 1 hrs', '1 hr', 'live', 30.77, 30.00, 'Urban Company also offers microwave cleaning $19, bathroom-only deep clean from $65, formaldehyde removal from $200 - none of which Kynd currently offers.', 'Price range $30-$50, used midpoint'),
  (1040, 1, 108, 'Floor Polishing 100 sqft', 'Polishing included - 2 worker(s), 2 hrs', '2 hrs', 'live', 192.31, 30.00, NULL, 'Hours estimated, not stated in source'),
  (1041, 1, 108, 'Floor Polishing 200 sqft', 'Polishing included - 2 worker(s), 3 hrs', '3 hrs', 'live', 307.69, 30.00, NULL, 'Hours estimated, not stated in source'),
  (1042, 1, 108, 'Floor Polishing 300 sqft', 'Polishing included - 2 worker(s), 4 hrs', '4 hrs', 'live', 423.08, 30.00, NULL, 'Hours estimated, not stated in source'),
  (1043, 1, 108, 'Floor Polishing 400 sqft', 'Polishing included - 3 worker(s), 5 hrs', '5 hrs', 'live', 461.54, 30.00, NULL, 'Hours estimated, not stated in source'),
  (1044, 1, 109, 'Single Mattress', 'Per item - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 53.85, 29.99, 'Urban Company: sofa cleaning $49, sofa+mattress combo $199 - Kynd currently has no direct sofa-cleaning line.', 'Hours estimated'),
  (1045, 1, 109, 'Super Single Mattress', 'Per item - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 69.23, 30.00, 'Urban Company: sofa cleaning $49, sofa+mattress combo $199 - Kynd currently has no direct sofa-cleaning line.', 'Hours estimated'),
  (1046, 1, 109, 'Queen Mattress', 'Per item - 1 worker(s), 0.75 hrs', '0.75 hrs', 'live', 92.31, 30.00, 'Urban Company: sofa cleaning $49, sofa+mattress combo $199 - Kynd currently has no direct sofa-cleaning line.', 'Hours estimated'),
  (1047, 1, 109, 'King Mattress', 'Per item - 1 worker(s), 0.75 hrs', '0.75 hrs', 'live', 115.38, 30.01, 'Urban Company: sofa cleaning $49, sofa+mattress combo $199 - Kynd currently has no direct sofa-cleaning line.', 'Hours estimated'),
  (1048, 1, 109, 'Super King Mattress', 'Per item - 1 worker(s), 1 hrs', '1 hr', 'live', 138.46, 30.00, 'Urban Company: sofa cleaning $49, sofa+mattress combo $199 - Kynd currently has no direct sofa-cleaning line.', 'Hours estimated'),
  (1049, 1, 109, 'Baby Cot', 'Per item - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 50.00, 30.00, 'Urban Company: sofa cleaning $49, sofa+mattress combo $199 - Kynd currently has no direct sofa-cleaning line.', 'Hours estimated'),
  (1050, 1, 110, 'Carpet 80cm x 120cm', 'Per item - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 61.54, 30.00, NULL, 'Hours estimated'),
  (1051, 1, 110, 'Carpet 150cm x 120cm', 'Per item - 1 worker(s), 0.75 hrs', '0.75 hrs', 'live', 100.00, 30.00, NULL, 'Hours estimated'),
  (1052, 1, 110, 'Carpet 180cm x 250cm', 'Per item - 1 worker(s), 1 hrs', '1 hr', 'live', 138.46, 30.00, NULL, 'Hours estimated'),
  (1053, 1, 110, 'Oversized / Custom Carpet', 'Per item, custom quote - 1 worker(s), 1.5 hrs', '1.5 hrs', 'live', 153.85, 30.00, NULL, 'Price is a floor ($200+); custom quote above this'),
  (1054, 1, 111, '1 Room + Hall', 'Per job - 1 worker(s), 1.5 hrs', '1.5 hrs', 'live', 138.46, 30.00, NULL, 'Hours estimated'),
  (1055, 1, 111, '2 Rooms + Hall', 'Per job - 1 worker(s), 2 hrs', '2 hrs', 'live', 215.38, 30.00, NULL, 'Hours estimated'),
  (1056, 1, 111, 'Day Curtain (per piece)', 'Per piece - 1 worker(s), 0.25 hrs', '0.25 hrs', 'live', 11.54, 29.98, NULL, 'Hours estimated'),
  (1057, 1, 111, 'Night Curtain (per piece)', 'Per piece - 1 worker(s), 0.25 hrs', '0.25 hrs', 'live', 19.23, 30.01, NULL, 'Hours estimated'),
  (1058, 3, 202, 'Body Massage 60 min', 'Female clients only, non-medical - 1 worker(s), 1 hrs', '1 hr', 'live', 61.54, 30.00, 'Urban Company runs 2 tiers: Signature $75-129 (matches Kynd) and Classic Relaxation $49-109 (cheaper, gender-neutral, no Kynd equivalent).', NULL),
  (1059, 3, 202, 'Body Massage 90 min', 'Female clients only, non-medical - 1 worker(s), 1.5 hrs', '1.5 hrs', 'live', 84.62, 29.99, 'Urban Company runs 2 tiers: Signature $75-129 (matches Kynd) and Classic Relaxation $49-109 (cheaper, gender-neutral, no Kynd equivalent).', NULL),
  (1060, 3, 202, 'Body Massage 120 min', 'Female clients only, non-medical - 1 worker(s), 2 hrs', '2 hrs', 'live', 107.69, 30.00, 'Urban Company runs 2 tiers: Signature $75-129 (matches Kynd) and Classic Relaxation $49-109 (cheaper, gender-neutral, no Kynd equivalent).', NULL),
  (1061, 3, 201, 'Head Massage 30 min', 'Female clients only, non-medical - 1 worker(s), 0.5 hrs', '0.5 hrs', 'live', 30.77, 30.00, 'Urban Company runs 2 tiers: Signature $75-129 (matches Kynd) and Classic Relaxation $49-109 (cheaper, gender-neutral, no Kynd equivalent).', NULL),
  (1062, 3, 201, 'Head Massage 45 min', 'Female clients only, non-medical - 1 worker(s), 0.75 hrs', '0.75 hrs', 'live', 42.31, 29.99, 'Urban Company runs 2 tiers: Signature $75-129 (matches Kynd) and Classic Relaxation $49-109 (cheaper, gender-neutral, no Kynd equivalent).', NULL),
  (1063, 3, 201, 'Head Massage 60 min', 'Female clients only, non-medical - 1 worker(s), 1 hrs', '1 hr', 'live', 53.85, 29.99, 'Urban Company runs 2 tiers: Signature $75-129 (matches Kynd) and Classic Relaxation $49-109 (cheaper, gender-neutral, no Kynd equivalent).', NULL),
  (1064, 5, 401, 'Office Cleaning - Ad-Hoc', 'One-off office clean, size/scope TBD', NULL, 'pending_rates', NULL, NULL, 'Not covered in the competitive scan yet - needs research once scope is defined.', 'Structure TBD with team - pricing not yet set.'),
  (1065, 5, 401, 'Office Cleaning - Weekly Contract', 'Recurring weekly office cleaning contract, TBD', NULL, 'pending_rates', NULL, NULL, 'Not covered in the competitive scan yet - needs research once scope is defined.', 'Structure TBD with team - pricing not yet set.'),
  (1066, 5, 401, 'Office Cleaning - Daily Contract', 'Recurring daily office cleaning contract, TBD', NULL, 'pending_rates', NULL, NULL, 'Not covered in the competitive scan yet - needs research once scope is defined.', 'Structure TBD with team - pricing not yet set.'),
  (1067, 5, 401, 'Office Cleaning - Move-In/Move-Out Deep Clean', 'Office move deep-clean, TBD', NULL, 'pending_rates', NULL, NULL, 'Not covered in the competitive scan yet - needs research once scope is defined.', 'Structure TBD with team - pricing not yet set.'),
  (1068, 6, 501, 'Pest Control - General Treatment (One-Time)', 'Ad-hoc general pest treatment, TBD', NULL, 'pending_rates', NULL, NULL, 'Urban Company has NOT entered pest control in Singapore (genuine whitespace per scan). Local specialists: Origin Exterminators, Rentokil, Ridpest - not yet price-checked.', 'Still sourcing a partner - pricing not yet set.'),
  (1069, 6, 501, 'Pest Control - General Treatment (Quarterly)', 'Recurring quarterly pest treatment contract, TBD', NULL, 'pending_rates', NULL, NULL, 'Urban Company has NOT entered pest control in Singapore (genuine whitespace per scan). Local specialists: Origin Exterminators, Rentokil, Ridpest - not yet price-checked.', 'Still sourcing a partner - pricing not yet set.'),
  (1070, 6, 501, 'Pest Control - Termite Treatment', 'Termite-specific treatment, TBD', NULL, 'pending_rates', NULL, NULL, 'Urban Company has NOT entered pest control in Singapore (genuine whitespace per scan). Local specialists: Origin Exterminators, Rentokil, Ridpest - not yet price-checked.', 'Still sourcing a partner - pricing not yet set.'),
  (1071, 6, 501, 'Pest Control - Rodent Control', 'Rodent control service, TBD', NULL, 'pending_rates', NULL, NULL, 'Urban Company has NOT entered pest control in Singapore (genuine whitespace per scan). Local specialists: Origin Exterminators, Rentokil, Ridpest - not yet price-checked.', 'Still sourcing a partner - pricing not yet set.'),
  (1072, 4, 301, 'Hair Service - Short Length', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1073, 4, 301, 'Hair Service - Long Length', NULL, NULL, 'live', 35.00, 31.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1074, 4, 301, 'Layer Haircut', NULL, NULL, 'live', 25.00, 28.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1075, 4, 301, 'U Shape Haircut', NULL, NULL, 'live', 20.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1076, 4, 301, 'Trimming', NULL, NULL, 'live', 20.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1077, 4, 301, 'Step Cut', NULL, NULL, 'live', 25.00, 28.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1078, 4, 303, 'Nail Art (avg of $10-$20 range)', NULL, NULL, 'live', 15.00, 33.33, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1079, 4, 303, 'Nail Extension', NULL, NULL, 'live', 110.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1080, 4, 304, 'Heena - Full Hand', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1081, 4, 304, 'Heena - Kids Design', NULL, NULL, 'live', 12.00, 33.33, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1082, 4, 305, 'Oxy Bleach - Face', NULL, NULL, 'live', 10.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1083, 4, 305, 'Oxy Bleach - Face & Neck', NULL, NULL, 'live', 15.00, 33.33, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1084, 4, 305, 'Oxy Bleach - Face, Neck & Back', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1085, 4, 305, 'Chandan Bleach - Face', NULL, NULL, 'live', 14.00, 28.57, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1086, 4, 305, 'Chandan Bleach - Face & Neck', NULL, NULL, 'live', 20.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1087, 4, 305, 'Chandan Bleach - Face, Neck & Back', NULL, NULL, 'live', 35.00, 31.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1088, 4, 306, 'VLCC Gold Facial', NULL, NULL, 'live', 80.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1089, 4, 306, 'VLCC Diamond Facial', NULL, NULL, 'live', 85.00, 29.41, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1090, 4, 306, 'VLCC Tan Facial', NULL, NULL, 'live', 75.00, 30.67, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1091, 4, 306, 'VLCC Anti Ageing Facial', NULL, NULL, 'live', 69.00, 30.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1092, 4, 306, 'Shahnaz Gold Facial', NULL, NULL, 'live', 55.00, 30.91, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1093, 4, 306, 'Fruits Facial', NULL, NULL, 'live', 55.00, 30.91, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1094, 4, 306, 'Natural Fruits Facial', NULL, NULL, 'live', 69.00, 30.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1095, 4, 306, 'O3 Facial', NULL, NULL, 'live', 129.00, 30.23, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1096, 4, 306, 'O3 Diamond Facial', NULL, NULL, 'live', 149.00, 30.20, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1097, 4, 306, 'O3 Detan Facial', NULL, NULL, 'live', 125.00, 29.60, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1098, 4, 306, 'Lotus Whitening Facial', NULL, NULL, 'live', 79.00, 30.38, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1099, 4, 306, 'Lotus Radiant Gold Facial', NULL, NULL, 'live', 70.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1100, 4, 306, 'Lotus Natural Glow Facial', NULL, NULL, 'live', 62.00, 30.65, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1101, 4, 307, 'Party Makeup', NULL, NULL, 'live', 60.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1102, 4, 307, 'Makeup & Hairstyle', NULL, NULL, 'live', 120.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1103, 4, 308, 'Pedicure', NULL, NULL, 'live', 35.00, 31.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1104, 4, 308, 'Manicure', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1105, 4, 308, 'Pedicure + Manicure', NULL, NULL, 'live', 60.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1106, 4, 309, 'Hair Spa (avg of $65-$100 range)', NULL, NULL, 'live', 82.50, 29.70, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1107, 4, 309, 'Hair Blow Dry', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1108, 4, 309, 'Hair Heena', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1109, 4, 309, 'Hair Color Touch Up (service charge only - colour product billed separately)', NULL, NULL, 'live', 20.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1110, 4, 310, 'Eyebrow Threading', NULL, NULL, 'live', 6.00, 33.33, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1111, 4, 310, 'Upper Lips Threading', NULL, NULL, 'live', 5.00, 20.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1112, 4, 310, 'Forehead Threading', NULL, NULL, 'live', 5.00, 20.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1113, 4, 310, 'Full Face Threading', NULL, NULL, 'live', 35.00, 31.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1114, 4, 311, 'Full Face Waxing (Hard Wax)', NULL, NULL, 'live', 45.00, 28.89, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1115, 4, 311, 'Full Arms Waxing', NULL, NULL, 'live', 35.00, 31.43, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1116, 4, 311, 'Full Legs Waxing', NULL, NULL, 'live', 40.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1117, 4, 311, 'Half Legs Waxing', NULL, NULL, 'live', 30.00, 30.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1118, 4, 311, 'Under Arm Waxing', NULL, NULL, 'live', 15.00, 33.33, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.'),
  (1119, 4, 311, 'Tummy & Back Waxing', NULL, NULL, 'live', 25.00, 28.00, 'Not yet researched - competitive scan covered cleaning/wellness only.', 'At-home service - partner brings full kit (saves the customer a salon trip); a real differentiator vs salon-only competitors.')
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  subcategory_id = VALUES(subcategory_id),
  name = VALUES(name),
  description = VALUES(description),
  duration = VALUES(duration),
  status = VALUES(status),
  default_partner_cost = VALUES(default_partner_cost),
  markup_pct_override = VALUES(markup_pct_override),
  competitor_reference = VALUES(competitor_reference),
  notes = VALUES(notes);

-- One flat pricing rule per service, holding the sheet's final sell price.
-- Pending-rates rows get custom_quote until a partner rate lands.
INSERT INTO service_pricing_rules (id, service_id, strategy, params)
VALUES
  (1001, 1001, 'flat', '{"amount": 30.0}'),
  (1002, 1002, 'flat', '{"amount": 45.0}'),
  (1003, 1003, 'flat', '{"amount": 60.0}'),
  (1004, 1004, 'flat', '{"amount": 60.0}'),
  (1005, 1005, 'flat', '{"amount": 75.0}'),
  (1006, 1006, 'flat', '{"amount": 90.0}'),
  (1007, 1007, 'flat', '{"amount": 120.0}'),
  (1008, 1008, 'flat', '{"amount": 60.0}'),
  (1009, 1009, 'flat', '{"amount": 90.0}'),
  (1010, 1010, 'flat', '{"amount": 120.0}'),
  (1011, 1011, 'flat', '{"amount": 188.0}'),
  (1012, 1012, 'flat', '{"amount": 275.0}'),
  (1013, 1013, 'flat', '{"amount": 320.0}'),
  (1014, 1014, 'flat', '{"amount": 312.0}'),
  (1015, 1015, 'flat', '{"amount": 456.0}'),
  (1016, 1016, 'flat', '{"amount": 608.0}'),
  (1017, 1017, 'flat', '{"amount": 560.0}'),
  (1018, 1018, 'flat', '{"amount": 816.0}'),
  (1019, 1019, 'flat', '{"amount": 1088.0}'),
  (1020, 1020, 'flat', '{"amount": 720.0}'),
  (1021, 1021, 'flat', '{"amount": 1020.0}'),
  (1022, 1022, 'flat', '{"amount": 1280.0}'),
  (1023, 1023, 'flat', '{"amount": 270.0}'),
  (1024, 1024, 'flat', '{"amount": 320.0}'),
  (1025, 1025, 'flat', '{"amount": 390.0}'),
  (1026, 1026, 'flat', '{"amount": 450.0}'),
  (1027, 1027, 'flat', '{"amount": 510.0}'),
  (1028, 1028, 'flat', '{"amount": 620.0}'),
  (1029, 1029, 'flat', '{"amount": 300.0}'),
  (1030, 1030, 'flat', '{"amount": 350.0}'),
  (1031, 1031, 'flat', '{"amount": 420.0}'),
  (1032, 1032, 'flat', '{"amount": 480.0}'),
  (1033, 1033, 'flat', '{"amount": 550.0}'),
  (1034, 1034, 'flat', '{"amount": 700.0}'),
  (1035, 1035, 'flat', '{"amount": 15.0}'),
  (1036, 1036, 'flat', '{"amount": 20.0}'),
  (1037, 1037, 'flat', '{"amount": 30.0}'),
  (1038, 1038, 'flat', '{"amount": 50.0}'),
  (1039, 1039, 'flat', '{"amount": 40.0}'),
  (1040, 1040, 'flat', '{"amount": 250.0}'),
  (1041, 1041, 'flat', '{"amount": 400.0}'),
  (1042, 1042, 'flat', '{"amount": 550.0}'),
  (1043, 1043, 'flat', '{"amount": 600.0}'),
  (1044, 1044, 'flat', '{"amount": 70.0}'),
  (1045, 1045, 'flat', '{"amount": 90.0}'),
  (1046, 1046, 'flat', '{"amount": 120.0}'),
  (1047, 1047, 'flat', '{"amount": 150.0}'),
  (1048, 1048, 'flat', '{"amount": 180.0}'),
  (1049, 1049, 'flat', '{"amount": 65.0}'),
  (1050, 1050, 'flat', '{"amount": 80.0}'),
  (1051, 1051, 'flat', '{"amount": 130.0}'),
  (1052, 1052, 'flat', '{"amount": 180.0}'),
  (1053, 1053, 'flat', '{"amount": 200.0}'),
  (1054, 1054, 'flat', '{"amount": 180.0}'),
  (1055, 1055, 'flat', '{"amount": 280.0}'),
  (1056, 1056, 'flat', '{"amount": 15.0}'),
  (1057, 1057, 'flat', '{"amount": 25.0}'),
  (1058, 1058, 'flat', '{"amount": 80.0}'),
  (1059, 1059, 'flat', '{"amount": 110.0}'),
  (1060, 1060, 'flat', '{"amount": 140.0}'),
  (1061, 1061, 'flat', '{"amount": 40.0}'),
  (1062, 1062, 'flat', '{"amount": 55.0}'),
  (1063, 1063, 'flat', '{"amount": 70.0}'),
  (1064, 1064, 'custom_quote', '{}'),
  (1065, 1065, 'custom_quote', '{}'),
  (1066, 1066, 'custom_quote', '{}'),
  (1067, 1067, 'custom_quote', '{}'),
  (1068, 1068, 'custom_quote', '{}'),
  (1069, 1069, 'custom_quote', '{}'),
  (1070, 1070, 'custom_quote', '{}'),
  (1071, 1071, 'custom_quote', '{}'),
  (1072, 1072, 'flat', '{"amount": 39.0}'),
  (1073, 1073, 'flat', '{"amount": 46.0}'),
  (1074, 1074, 'flat', '{"amount": 32.0}'),
  (1075, 1075, 'flat', '{"amount": 26.0}'),
  (1076, 1076, 'flat', '{"amount": 26.0}'),
  (1077, 1077, 'flat', '{"amount": 32.0}'),
  (1078, 1078, 'flat', '{"amount": 20.0}'),
  (1079, 1079, 'flat', '{"amount": 143.0}'),
  (1080, 1080, 'flat', '{"amount": 39.0}'),
  (1081, 1081, 'flat', '{"amount": 16.0}'),
  (1082, 1082, 'flat', '{"amount": 13.0}'),
  (1083, 1083, 'flat', '{"amount": 20.0}'),
  (1084, 1084, 'flat', '{"amount": 39.0}'),
  (1085, 1085, 'flat', '{"amount": 18.0}'),
  (1086, 1086, 'flat', '{"amount": 26.0}'),
  (1087, 1087, 'flat', '{"amount": 46.0}'),
  (1088, 1088, 'flat', '{"amount": 104.0}'),
  (1089, 1089, 'flat', '{"amount": 110.0}'),
  (1090, 1090, 'flat', '{"amount": 98.0}'),
  (1091, 1091, 'flat', '{"amount": 90.0}'),
  (1092, 1092, 'flat', '{"amount": 72.0}'),
  (1093, 1093, 'flat', '{"amount": 72.0}'),
  (1094, 1094, 'flat', '{"amount": 90.0}'),
  (1095, 1095, 'flat', '{"amount": 168.0}'),
  (1096, 1096, 'flat', '{"amount": 194.0}'),
  (1097, 1097, 'flat', '{"amount": 162.0}'),
  (1098, 1098, 'flat', '{"amount": 103.0}'),
  (1099, 1099, 'flat', '{"amount": 91.0}'),
  (1100, 1100, 'flat', '{"amount": 81.0}'),
  (1101, 1101, 'flat', '{"amount": 78.0}'),
  (1102, 1102, 'flat', '{"amount": 156.0}'),
  (1103, 1103, 'flat', '{"amount": 46.0}'),
  (1104, 1104, 'flat', '{"amount": 39.0}'),
  (1105, 1105, 'flat', '{"amount": 78.0}'),
  (1106, 1106, 'flat', '{"amount": 107.0}'),
  (1107, 1107, 'flat', '{"amount": 39.0}'),
  (1108, 1108, 'flat', '{"amount": 39.0}'),
  (1109, 1109, 'flat', '{"amount": 26.0}'),
  (1110, 1110, 'flat', '{"amount": 8.0}'),
  (1111, 1111, 'flat', '{"amount": 6.0}'),
  (1112, 1112, 'flat', '{"amount": 6.0}'),
  (1113, 1113, 'flat', '{"amount": 46.0}'),
  (1114, 1114, 'flat', '{"amount": 58.0}'),
  (1115, 1115, 'flat', '{"amount": 46.0}'),
  (1116, 1116, 'flat', '{"amount": 52.0}'),
  (1117, 1117, 'flat', '{"amount": 39.0}'),
  (1118, 1118, 'flat', '{"amount": 20.0}'),
  (1119, 1119, 'flat', '{"amount": 32.0}')
ON DUPLICATE KEY UPDATE
  service_id = VALUES(service_id),
  strategy = VALUES(strategy),
  params = VALUES(params);

-- Crew size and rate basis, derived from the sheet text above so the storefront
-- variant picker can show "1 worker · day rate". Only fills rows still NULL, so
-- a value edited in the superadmin console survives a re-seed. Kept in sync with
-- backend/db/migrations/004-service-crew-rate.sql.
UPDATE catalog_services
   SET worker_count = CAST(SUBSTRING_INDEX(REGEXP_SUBSTR(description, '[0-9]+ worker'), ' ', 1) AS UNSIGNED)
 WHERE worker_count IS NULL
   AND description REGEXP '[0-9]+ worker';

UPDATE catalog_services
   SET rate_type = CASE
     WHEN notes LIKE '%day rate applied here%' THEN 'day_rate'
     WHEN description LIKE 'Per unit%' THEN 'per_unit'
     WHEN description LIKE 'Per job%' THEN 'per_job'
     WHEN notes LIKE '%Monthly package price%'
       OR notes LIKE '%sessions combined%'
       OR description LIKE '%session bundle%' THEN 'package'
     ELSE NULL
   END
 WHERE rate_type IS NULL;
